camera:
  device: /dev/video0
  width: 1280
  height: 720
detector:
  model_path: ./model/best-int8.tflite
  confidence_threshold: 0.5
  iou_threshold: 0.45
  size: 640
server:
  address: 0.0.0.0:9090
  key_path: ./tools/cert/localhost.key
  cert_path: ./tools/cert/localhost.crt
  password: f2b94662c69f9440090c9d79aa12f0f10a98b269257c2f386725936cbaa8c60d