name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'web-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: web-app/package-lock.json

      - name: Build
        run: |
          cd web-app
          ng build --cross-origin anonymous --base-href "/autodrone/"


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
